In [ ]:
import sqlite3
import pandas as pd

pd.set_option('display.max_columns', None)

In [ ]:
connection = sqlite3.connect('../dbs/bronze.db') 
connection.cursor().execute('DROP TABLE competitions')
connection.cursor().execute('DROP TABLE matches')

In [4]:
connection = sqlite3.connect('../dbs/bronze.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('SELECT * FROM matches', connection)

# 3. Always close the connection when finished
connection.close()

df

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,competition_id,competition_country_name,competition_name,competition,season_id,season,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version,data_valid_from_utc,data_valid_to_utc
0,3857276,2022-12-01,15:00:00.000,1,2,available,available,2026-05-04 01:46:04.664252,2026-05-04 01:50:33.318123,3,43,International,FIFA World Cup,International - FIFA World Cup,106,2022,1833,Canada,male,F,40,Canada,788,Morocco,male,NaN,154,Morocco,10,Group Stage,1000838,Al Thumama Stadium,185,Qatar,2638.0,Raphael Claus,31.0,Brazil,John Herdman,Walid Regragui,4435,John Herdman,NaN,1975-07-19,68,England,1000518,Walid Regragui,NaN,1975-09-23,154,Morocco,1.1.0,2,2,2026-08-05 10:38:39.711996,None
1,3857271,2022-11-21,13:00:00.000,6,2,available,available,2026-05-04 01:40:47.671394,2026-05-04 01:43:30.216315,1,43,International,FIFA World Cup,International - FIFA World Cup,106,2022,768,England,male,B,68,England,797,Iran,male,B,107,"Iran, Islamic Republic of",10,Group Stage,1000253,Sheikh Khalifa International Stadium,185,Qatar,2638.0,Raphael Claus,31.0,Brazil,Gareth Southgate,Carlos Manuel Brito Leal Queiróz,277,Gareth Southgate,NaN,1970-09-03,68,England,645,Carlos Manuel Brito Leal Queiróz,Carlos Queiroz,1953-03-01,183,Portugal,1.1.0,2,2,2026-08-05 10:38:39.711996,None
2,3857296,2022-12-01,15:00:00.000,0,0,available,available,2026-05-04 01:44:02.255386,2026-05-04 01:50:06.343225,3,43,International,FIFA World Cup,International - FIFA World Cup,106,2022,785,Croatia,male,F,56,Croatia,782,Belgium,male,F,22,Belgium,10,Group Stage,1000793,Ahmad bin Ali Stadium,185,Qatar,8.0,Anthony Taylor,68.0,England,Zlatko Dalić,Roberto Martínez Montoliú,307,Zlatko Dalić,NaN,1966-10-26,56,Croatia,263,Roberto Martínez Montoliú,Roberto Martínez,1973-07-13,214,Spain,1.1.0,2,2,2026-08-05 10:38:39.711996,None
3,3857274,2022-11-25,16:00:00.000,1,1,available,available,2026-05-04 01:43:00.444702,2026-05-04 01:50:07.646458,2,43,International,FIFA World Cup,International - FIFA World Cup,106,2022,941,Netherlands,male,A,160,Netherlands,3565,Ecuador,male,A,65,Ecuador,10,Group Stage,1000253,Sheikh Khalifa International Stadium,185,Qatar,2311.0,Mustapha Ghorbal,4.0,Algeria,Louis van Gaal,Gustavo Julio Alfaro,788,Louis van Gaal,NaN,1951-08-08,160,Netherlands,2881,Gustavo Julio Alfaro,Gustavo Alfaro,1962-08-14,11,Argentina,1.1.0,2,2,2026-08-05 10:38:39.711996,None
4,3857255,2022-12-01,19:00:00.000,2,1,available,available,2026-05-04 01:42:55.630428,2026-05-04 01:49:36.594944,3,43,International,FIFA World Cup,International - FIFA World Cup,106,2022,778,Japan,male,E,114,Japan,772,Spain,male,E,214,Spain,10,Group Stage,1000253,Sheikh Khalifa International Stadium,185,Qatar,2366.0,Victor Miguel de Freitas Gomes,211.0,South Africa,Hajime Moriyasu,Luis Enrique Martínez García,5699,Hajime Moriyasu,NaN,1968-08-23,114,Japan,793,Luis Enrique Martínez García,Luis Enrique,1970-05-08,214,Spain,1.1.0,2,2,2026-08-05 10:38:39.711996,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,3857291,2022-11-23,16:00:00.000,7,0,available,available,2026-05-03 16:08:38.580488,2026-05-03 16:12:13.412295,1,43,International,FIFA World Cup,International - FIFA World Cup,106,2022,772,Spain,male,E,214,Spain,795,Costa Rica,male,E,54,Costa Rica,10,Group Stage,1000838,Al Thumama Stadium,185,Qatar,NaN,NaN,NaN,NaN,Luis Enrique Martínez García,Luis Fernando Suárez Guzman,793,Luis Enrique Martínez García,Luis Enrique,1970-05-08,214,Spain,3094,Luis Fernando Suárez Guzman,Luis Fernando Suárez,1959-12-23,49,Colombia,1.1.0,2,2,2026-08-05 10:38:39.711996,None
60,3857281,2022-11-27,16:00:00.000,4,1,available,available,2026-05-04 01:47:00.853566,2026-05-04 01:51:52.104873,2,43,International,FIFA World Cup,International - FIFA World Cup,106,2022,785,Croatia,male,F,56,Croatia,1833,Canada,male,F,40,Canada,10,Group Stage,1000253,Sheikh Khalifa International Stadium,185,Qatar,1814.0,Andrés Matonte,242.0,Uruguay,Zlatko Dalić,John Herdman,307,Zlatko Dalić,NaN,1966-10-26,56,Croatia,4435,John Herdman,NaN,1975-07-19,68,England,1.1.0,2,2,2026-08-05 10:38:39.711996,None
61,3857280,2022-12-02,19:00:00.000,1,0,available,available,2026-05-03 15:41:58.839286,2026-05-03 15:44:07.018244,3,43,International,FIFA World Cup,International - FIFA World Cup,106,2022,2722,Cameroon,male,G,39,Cameroon,781,Brazil,male,G,31,Brazil,10,Group Stage,1001114,Lusail Stadium,185,Qatar,438.0,Ismail Elfath,241.0,United States of America,Rigobert Song Bahanag,Adenor Leonardo Bacchi,1001250,Rigobert Song Bahanag,NaN,1976-07-01,39,Cameroon,547,Adenor Leonardo Bacchi,Tite,1961-05-25,31,Brazil,1.1.0,2,2,2026-08-05 10:38:39.711996,None
62,3857279,2022-11-22,19:00:00.000,4,1,available,available,2026-05-04 01:44:53.405576,2026-05-04 01:50:33.615237,1,43,International,FIFA World Cup,International - FIFA World Cup,106,2022,771,France,male,D,78,France,792,Australia,male,D,14,Australia,10,Group Stage,117897,Al Janoub Stadium,185,Qatar,2366.0,Victor Miguel de Freitas Gomes,211.0,South Africa,Didier Deschamps,Graham James Arnold,545,Didier Deschamps,NaN,1968-10-15,78,France,5696,Graham James Arnold,NaN,1963-08-03,14,Australia,1.1.0,2,2,2026-08-05 10:38:39.711996,None
63,3857262,2022-12-02,15:00:00.000,2,1,available,available,2026-05-03 16:05:21.572751,2026-05-03 16:07:48.636747,3,43,International,FIFA World Cup,International - FIFA World Cup,106,2022,791,South Korea,male,H,121,Korea (South),780,Portugal,male,H,183,Portugal,10,Group Stage,94425,Education City Stadium,185,Qatar,1094.0,Facundo Tello Figueroa,11.0,Argentina,Paulo Jorge Gomes Bento,Fernando Manuel Fernandes da Costa Santos,5688,Paulo Jorge Gomes Bento,Paulo Bento,1969-06-20,183,Portugal,607,Fernando Manuel Fernandes da Costa Santos,Fernando Santos,1954-10-10,183,Portugal,1.1.0,2,2,2026-08-05 10:38:39.711996,None

In [33]:
connection = sqlite3.connect('../dbs/silver.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('SELECT * FROM combined WHERE id = "001b722a-126d-4e94-a20b-55ccfc3f45d8"', connection)

# 3. Always close the connection when finished
connection.close()

df

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_id,match_date,kick_off,home_score,away_score,match_status,match_week,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,id,period,timestamp,minute,second,type,possession,possession_team,play_pattern,team,team_id,player,player_id,position,tactics,location,duration,under_pressure,off_camera,out,counterpress,pass_recipient,pass_recipient_id,pass_length,pass_angle,pass_height,pass_end_location,pass_body_part,pass_type,pass_outcome,pass_technique,pass_switch,pass_cross,pass_assisted_shot_id,pass_shot_assist,pass_inswinging,pass_outswinging,pass_cut_back,pass_deflected,pass_through_ball,carry_end_location,shot_end_location,shot_statsbomb_xg,shot_outcome,shot_type,shot_body_part,shot_technique,shot_first_time,shot_key_pass_id,shot_aerial_won,shot_freeze_frame,goalkeeper_position,goalkeeper_type,goalkeeper_outcome,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_technique,dribble_outcome,dribble_overrun,dribble_nutmeg,duel_type,duel_outcome,50_50,block_deflection,block_offensive,clearance_head,clearance_left_foot,clearance_right_foot,clearance_body_part,clearance_aerial_won,ball_receipt_outcome,ball_recovery_recovery_failure,ball_recovery_offensive,foul_committed_type,foul_committed_advantage,foul_committed_card,foul_committed_penalty,foul_won_advantage,foul_won_defensive,interception_outcome,miscontrol_aerial_won,injury_stoppage_in_chain,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,related_events
0,43,106,International,FIFA World Cup,male,0,1,2022,3857267,2022-11-29,15:00:00.000,1,2,available,3,3565,Ecuador,male,A,65,Ecuador,787,Senegal,male,A,202,Senegal,10,Group Stage,1000253,Sheikh Khalifa International Stadium,185,Qatar,76,Clément Turpin,78,France,Gustavo Julio Alfaro,Aliou Cissé,2881,Gustavo Julio Alfaro,Gustavo Alfaro,1962-08-14,11,Argentina,635,Aliou Cissé,None,1976-03-24,202,Senegal,001b722a-126d-4e94-a20b-55ccfc3f45d8,1,00:03:36.020,3,36,Carry,8,Ecuador,From Goal Kick,Senegal,787,Pathé Ismaël Ciss,31751,Right Defensive Midfield,null,"[36.7, 24.5]",2.618976,1,None,None,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,"[37.7, 8.8]",null,None,None,None,None,None,None,None,None,null,None,None,None,None,null,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[""ae18bca7-36a4-4fdd-b7ed-f9f6e8b12911"", ""833e..."

In [4]:
import sqlite3
import pandas as pd

pd.set_option('display.max_columns', None)

combined_passes_query = f"""
 -- SQLite
SELECT 
    *
FROM 
    combined_passes
"""

In [5]:
connection = sqlite3.connect('../dbs/gold.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query(combined_passes_query, connection)

# 3. Always close the connection when finished
connection.close()

df

,competition_id,season_id,country_name,competition_name,season_name,match_id,match_date,kick_off,home_score,away_score,match_week,home_team,away_team,winning_team_id,winning_team,competition_stage,id,period,which_half,timestamp,minute,second,type,possession,possession_team,play_pattern,team,team_id,part_of_winning_team,player,player_id,position,location,duration,under_pressure,off_camera,out,counterpress,pass_recipient,pass_recipient_id,pass_length,pass_angle,pass_direction,pass_height,pass_end_location,pass_end_sector,pass_end_sector_rank,pass_body_part,pass_type,pass_outcome,pass_technique,pass_switch,pass_cross,pass_assisted_shot_id,pass_shot_assist,pass_inswinging,pass_outswinging,pass_cut_back,pass_deflected,pass_through_ball
0,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,00391272-8571-43e0-be07-d5a0b48c384f,1,1st Half,00:10:39.457,10,39,Pass,24,England,Regular Play,England,768,1,Jordan Pickford,3468,Goalkeeper,"[31.1, 46.4]",1.549342,NaN,NaN,None,NaN,Harry Maguire,3336.0,15.435349,-1.136126,Forward,Ground Pass,"[37.6, 32.4]",Defensive 3rd,3,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
1,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,00df2def-4426-45b6-9305-8f6ef9a6a394,1,1st Half,00:37:05.151,37,5,Pass,61,England,Regular Play,England,768,1,Phil Foden,4354,Right Wing,"[74.7, 72.4]",1.309154,NaN,NaN,None,NaN,Jordan Brian Henderson,3532.0,13.461427,0.470292,Forward,Ground Pass,"[86.7, 78.5]",Final 3rd,1,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
2,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,0117d34f-2ee9-4681-83f7-bb3e1c06f091,1,1st Half,00:21:39.019,21,39,Pass,35,England,From Free Kick,England,768,1,Jordan Brian Henderson,3532,Right Center Midfield,"[110.0, 78.8]",1.497853,NaN,NaN,None,NaN,Kyle Walker,3205.0,14.257980,-2.951075,Backward,Ground Pass,"[96.0, 76.1]",Final 3rd,1,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
3,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,01416e43-e4da-4b30-a712-1792772e20fa,2,2nd Half,00:48:12.399,93,12,Pass,156,England,From Free Kick,England,768,1,Jude Bellingham,30714,Left Center Midfield,"[56.0, 33.1]",0.874044,NaN,NaN,None,NaN,Jack Grealish,9638.0,18.519450,-0.113639,Forward,Ground Pass,"[74.4, 31.0]",Middle 3rd,2,Right Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
4,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,01fb8c30-333b-4290-a84b-caefbb85e6b3,2,2nd Half,00:20:44.941,65,44,Pass,116,England,Regular Play,England,768,1,Trent Alexander-Arnold,3664,Right Back,"[34.1, 55.9]",1.565596,1.0,NaN,None,NaN,Marcus Rashford,3318.0,13.519245,0.370891,Forward,High Pass,"[46.7, 60.8]",Middle 3rd,2,NaN,Recovery,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,fe7cd9b5-195a-4fe3-b48d-18e15f6b5b5c,1,1st Half,00:02:03.976,2,3,Pass,9,England,Regular Play,England,768,1,Jordan Pickford,3468,Goalkeeper,"[23.8, 37.6]",0.980531,NaN,NaN,None,NaN,Harry Maguire,3336.0,7.473286,-1.355030,Forward,Ground Pass,"[25.4, 30.3]",Defensive 3rd,3,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
977,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,fe84aab4-fe90-41df-a663-e162a536f67b,2,2nd Half,00:02:10.417,47,10,Pass,92,England,From Free Kick,England,768,1,Luke Shaw,3382,Left Back,"[34.1, 3.1]",1.650400,NaN,NaN,None,NaN,Harry Maguire,3336.0,15.071164,2.459598,Backward,Ground Pass,"[22.4, 12.6]",Defensive 3rd,3,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
978,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,ff0b51d4-3173-46e4-b1e5-4b19bfc71e95,2,2nd Half,00:20:03.976,65,3,Pass,114,Wales,From Free Kick,Wales,907,0,Daniel Ward,9914,Goalkeeper,"[26.0, 15.8]",3.701090,NaN,NaN,None,NaN,Kieffer Roberto Francisco Moore,3853.0,63.764020,-0.182939,Forward,Ground Pass,"[88.7, 4.2]",Final 3rd,1,Right Foot,Free Kick,Incomplete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
979,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,ff2ca628-2b5a-4620-b3a4-7b5db9e5f8d9,1,1st Half,00:31:48.157,31,48,Pass,55,Wales,Regular Play,Wales,907,0,Joe Rodon,11250,Left Center Back,"[21.8, 28.7]",1.309225,NaN,NaN,None,NaN,Ben Davies,3086.0,22.986954,-1.111040,Forward,Ground Pass,"[32.0, 8.1]",Defensive 3rd,3,Right Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
980,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,ff86d751-f1e9-4018-a693-1940c91d1389,1,1st Half,00:25:21.961,25,21,Pass,40,England,Regular Play,England,768,1,Kyle Walker,3205,Right Back,"[81.0, 65.2]",0.984402,NaN,NaN,None,NaN,Phil Foden,4354.0,13.403358,0.949680,Forward,Ground Pass,"[88.8, 76.1]",Final 3rd,1,Right Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN

In [6]:
df.to_csv('passes.csv')