In [1]:
import sqlite3
import pandas as pd

pd.set_option('display.max_columns', None)

In [11]:
comp_match_query = f"""
    SELECT 
        c.country_name
        ,c.competition_name	
        ,c.competition_gender
        ,c.competition_youth
        ,c.competition_international
        ,c.season_name
        ,m.*
    FROM 
        competitions c
    LEFT JOIN 
        matches m
    ON 
        c.competition_id = m.competition_id
    AND 
        c.season_id = m.season_id
"""

In [ ]:
connection = sqlite3.connect('../dbs/bronze.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query(comp_match_query, connection)

# 3. Always close the connection when finished
connection.close()

df

,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_id,match_date,kick_off,home_score,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,International,FIFA World Cup,male,0,1,2022,3857254,2022-11-22,13:00:00.000,0,...,Denmark,1001303,Jalel Kadri,NaN,NaN,232,Tunisia,1.1.0,2,2
1,International,FIFA World Cup,male,0,1,2022,3857255,2022-12-01,19:00:00.000,2,...,Japan,793,Luis Enrique Martínez García,Luis Enrique,1970-05-08,214,Spain,1.1.0,2,2
2,International,FIFA World Cup,male,0,1,2022,3857256,2022-12-02,19:00:00.000,2,...,Serbia,2832,Murat Yakin,NaN,1974-09-15,221,Switzerland,1.1.0,2,2
3,International,FIFA World Cup,male,0,1,2022,3857257,2022-11-30,15:00:00.000,1,...,Australia,255,Kasper Hjulmand,NaN,1972-04-09,61,Denmark,1.1.0,2,2
4,International,FIFA World Cup,male,0,1,2022,3857258,2022-11-24,19:00:00.000,2,...,Brazil,5908,Dragan Stojković,NaN,1965-03-03,203,Serbia,1.1.0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,International,FIFA World Cup,male,0,1,2022,3869486,2022-12-10,17:00:00.000,1,...,Morocco,607,Fernando Manuel Fernandes da Costa Santos,Fernando Santos,1954-10-10,183,Portugal,1.1.0,2,2
60,International,FIFA World Cup,male,0,1,2022,3869519,2022-12-13,21:00:00.000,3,...,Argentina,307,Zlatko Dalić,NaN,1966-10-26,56,Croatia,1.1.0,2,2
61,International,FIFA World Cup,male,0,1,2022,3869552,2022-12-14,21:00:00.000,2,...,France,1001086,Hoalid Regragui,NaN,1975-09-23,154,Morocco,1.1.0,2,2
62,International,FIFA World Cup,male,0,1,2022,3869684,2022-12-17,17:00:00.000,2,...,Croatia,1000518,Walid Regragui,NaN,1975-09-23,154,Morocco,1.1.0,2,2
63,International,FIFA World Cup,male,0,1,2022,3869685,2022-12-18,17:00:00.000,3,...,Argentina,545,Didier Deschamps,NaN,1968-10-15,78,France,1.1.0,2,2

In [19]:
connection = sqlite3.connect('../dbs/intermediate.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('SELECT * FROM complete', connection)

# 3. Always close the connection when finished
connection.close()

In [20]:
df

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_available,...,foul_won_advantage,foul_won_defensive,interception_outcome,miscontrol_aerial_won,injury_stoppage_in_chain,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,related_events
0,43,106,International,FIFA World Cup,male,0,1,2022,2026-05-04 01:48:57.914346,2026-05-04 01:48:57.914346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""4c06e685-da09-41f6-b643-7b4340a4c15b""]"
1,43,106,International,FIFA World Cup,male,0,1,2022,2026-05-04 01:48:57.914346,2026-05-04 01:48:57.914346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""0422b661-9d4a-4187-bf26-8fbbe7e2df2c""]"
2,43,106,International,FIFA World Cup,male,0,1,2022,2026-05-04 01:48:57.914346,2026-05-04 01:48:57.914346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""b0e85b27-b397-4ce4-884c-16fc3162a02e""]"
3,43,106,International,FIFA World Cup,male,0,1,2022,2026-05-04 01:48:57.914346,2026-05-04 01:48:57.914346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""39a6220d-0f00-44f9-af9e-f27374d32404"", ""790f..."
4,43,106,International,FIFA World Cup,male,0,1,2022,2026-05-04 01:48:57.914346,2026-05-04 01:48:57.914346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""6233f0ff-cb60-4190-addb-385abc5ea408""]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234632,43,106,International,FIFA World Cup,male,0,1,2022,2026-05-04 01:48:57.914346,2026-05-04 01:48:57.914346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""2c406b42-7386-4c44-97bf-5f10e6114e33"", ""af9f..."
234633,43,106,International,FIFA World Cup,male,0,1,2022,2026-05-04 01:48:57.914346,2026-05-04 01:48:57.914346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""77783729-5fc4-4713-8f72-418a8b185f96""]"
234634,43,106,International,FIFA World Cup,male,0,1,2022,2026-05-04 01:48:57.914346,2026-05-04 01:48:57.914346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""e487d5da-f8be-48d2-83ea-4540a4b399cc""]"
234635,43,106,International,FIFA World Cup,male,0,1,2022,2026-05-04 01:48:57.914346,2026-05-04 01:48:57.914346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""d91ade26-2a7d-45e3-8af1-1022d4db65ee""]"
234636,43,106,International,FIFA World Cup,male,0,1,2022,2026-05-04 01:48:57.914346,2026-05-04 01:48:57.914346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""8509af90-b5d2-4dbc-b3d9-6de8561f9277""]"

In [ ]:
connection = sqlite3.connect('../dbs/bronze.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('SELECT * FROM events', connection)

# 3. Always close the connection when finished
connection.close()

In [15]:
df

,id,period,timestamp,minute,second,type,possession,possession_team,play_pattern,team,...,foul_won_defensive,interception_outcome,miscontrol_aerial_won,injury_stoppage_in_chain,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,related_events,match_id
0,1f60fe1e-0340-49e2-975e-f16f54c5da1a,1,00:00:00.000,0,0,Starting XI,1,Canada,Regular Play,Canada,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,null,3857276
1,d5ffdab0-a19a-497e-a0f6-d5403bfcc2b5,1,00:00:00.000,0,0,Starting XI,1,Canada,Regular Play,Morocco,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,null,3857276
2,c6dcab53-5a07-4a6e-ab8b-64e9f9133d19,1,00:00:00.000,0,0,Half Start,1,Canada,Regular Play,Morocco,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""396c6ebb-5ba7-415c-ba37-88ff51f7c737""]",3857276
3,396c6ebb-5ba7-415c-ba37-88ff51f7c737,1,00:00:00.000,0,0,Half Start,1,Canada,Regular Play,Canada,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""c6dcab53-5a07-4a6e-ab8b-64e9f9133d19""]",3857276
4,f2023e55-3c53-44be-9826-8aa0a0ac355f,2,00:00:00.000,45,0,Half Start,85,Canada,From Throw In,Morocco,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""ffe7e95d-9ded-4ba0-9d8f-e8ca18513419""]",3857276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234632,056c29c8-ef1c-407c-ba62-57a8b0dca7cc,2,00:36:13.753,81,13,Substitution,125,South Korea,From Throw In,South Korea,...,NaN,NaN,NaN,NaN,Tactical,103.0,Ui-Jo Hwang,29966.0,null,3857262
234633,87843ec2-ebab-4ad8-ba7b-3b53fd356f03,2,00:36:13.762,81,13,Substitution,125,South Korea,From Throw In,Portugal,...,NaN,NaN,NaN,NaN,Tactical,103.0,William Silva de Carvalho,5214.0,null,3857262
234634,650af2c9-a2f8-43ec-add6-d238944382ec,2,00:36:13.790,81,13,Substitution,125,South Korea,From Throw In,Portugal,...,NaN,NaN,NaN,NaN,Tactical,103.0,Bernardo Mota Veiga de Carvalho e Silva,3193.0,null,3857262
234635,7f9e9eda-c56c-4100-9ee0-b19294ffc3fc,2,00:47:46.061,92,46,Substitution,149,Portugal,From Kick Off,South Korea,...,NaN,NaN,NaN,NaN,Tactical,103.0,Yu-Min Cho,99479.0,null,3857262
234636,9ca0ec62-4377-4d15-a255-677af0f0f97b,2,00:47:36.651,92,36,Bad Behaviour,148,South Korea,Regular Play,South Korea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,null,3857262

In [ ]:
import sqlite3

# Connect to the database file
conn = sqlite3.connect('../dbs/bronze.db')
cursor = conn.cursor()

# Get list of all tables
cursor.execute("""DELETE FROM staging_competitions""")
conn.commit()
conn.close()

In [ ]:
import sqlite3

# Connect to the database file
conn = sqlite3.connect('../dbs/bronze.db')
cursor = conn.cursor()

# Get list of all tables
cursor.execute("""DELETE FROM competitions""")
conn.commit()
conn.close()

In [1]:
import sqlite3

def create_bronze_table_structure():
    _dict = {
        'bronze':['competitions', 'matches', 'events']
    }
    for schema, table_list in _dict.items():
        with sqlite3.connect(f"../dbs/{schema}.db") as conn:
            cursor = conn.cursor()

            cursor.execute("ATTACH DATABASE '../dbs/staging.db' AS staging")

            try:
                for table in table_list:
                    cursor.execute("""
                        SELECT sql
                        FROM staging.sqlite_master
                        WHERE type = 'table'
                        AND name = ?
                    """, (table,))

                    row = cursor.fetchone()
                    if row is None:
                        print(f"{schema}: '{table}' not found in staging.db")
                        continue

                    create_sql = row[0]

                    cursor.execute(f'DROP TABLE IF EXISTS "{table}"')
                    cursor.execute(create_sql)

            finally:
                cursor.execute("DETACH DATABASE staging")

In [2]:
create_bronze_table_structure()

bronze: 'matches' not found in staging.db
bronze: 'events' not found in staging.db