In [2]:
import sqlite3
import pandas as pd

pd.set_option('display.max_columns', None)

In [ ]:
connection = sqlite3.connect('../dbs/bronze.db') 
connection.cursor().execute('DROP TABLE competitions')
connection.cursor().execute('DROP TABLE matches')

In [32]:
connection = sqlite3.connect('../dbs/silver.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('SELECT COUNT(*) FROM events', connection)

# 3. Always close the connection when finished
connection.close()

df

   COUNT(*)
0    234637

In [33]:
connection = sqlite3.connect('../dbs/silver.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('SELECT * FROM combined WHERE id = "001b722a-126d-4e94-a20b-55ccfc3f45d8"', connection)

# 3. Always close the connection when finished
connection.close()

df

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_id,match_date,kick_off,home_score,away_score,match_status,match_week,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,id,period,timestamp,minute,second,type,possession,possession_team,play_pattern,team,team_id,player,player_id,position,tactics,location,duration,under_pressure,off_camera,out,counterpress,pass_recipient,pass_recipient_id,pass_length,pass_angle,pass_height,pass_end_location,pass_body_part,pass_type,pass_outcome,pass_technique,pass_switch,pass_cross,pass_assisted_shot_id,pass_shot_assist,pass_inswinging,pass_outswinging,pass_cut_back,pass_deflected,pass_through_ball,carry_end_location,shot_end_location,shot_statsbomb_xg,shot_outcome,shot_type,shot_body_part,shot_technique,shot_first_time,shot_key_pass_id,shot_aerial_won,shot_freeze_frame,goalkeeper_position,goalkeeper_type,goalkeeper_outcome,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_technique,dribble_outcome,dribble_overrun,dribble_nutmeg,duel_type,duel_outcome,50_50,block_deflection,block_offensive,clearance_head,clearance_left_foot,clearance_right_foot,clearance_body_part,clearance_aerial_won,ball_receipt_outcome,ball_recovery_recovery_failure,ball_recovery_offensive,foul_committed_type,foul_committed_advantage,foul_committed_card,foul_committed_penalty,foul_won_advantage,foul_won_defensive,interception_outcome,miscontrol_aerial_won,injury_stoppage_in_chain,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,related_events
0,43,106,International,FIFA World Cup,male,0,1,2022,3857267,2022-11-29,15:00:00.000,1,2,available,3,3565,Ecuador,male,A,65,Ecuador,787,Senegal,male,A,202,Senegal,10,Group Stage,1000253,Sheikh Khalifa International Stadium,185,Qatar,76,Clément Turpin,78,France,Gustavo Julio Alfaro,Aliou Cissé,2881,Gustavo Julio Alfaro,Gustavo Alfaro,1962-08-14,11,Argentina,635,Aliou Cissé,None,1976-03-24,202,Senegal,001b722a-126d-4e94-a20b-55ccfc3f45d8,1,00:03:36.020,3,36,Carry,8,Ecuador,From Goal Kick,Senegal,787,Pathé Ismaël Ciss,31751,Right Defensive Midfield,null,"[36.7, 24.5]",2.618976,1,None,None,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,"[37.7, 8.8]",null,None,None,None,None,None,None,None,None,null,None,None,None,None,null,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[""ae18bca7-36a4-4fdd-b7ed-f9f6e8b12911"", ""833e..."