In [2]:
import sqlite3
import pandas as pd

In [3]:
connection = sqlite3.connect('../dbs/competitions.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('SELECT * FROM competitions', connection)

# 3. Always close the connection when finished
connection.close()


df

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,0,0,2023/2024,2024-09-28 20:46:38.893391,2025-11-15 23:17:41.827093,2025-11-15 23:17:41.827093,2024-09-28 20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,0,0,2015/2016,2024-05-19 11:11:14.192381,NaN,NaN,2024-05-19 11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,0,1,2023,2026-05-12 21:18:08.827431,2026-05-02 02:07:18.902396,2026-05-02 02:07:18.902396,2026-05-12 21:18:08.827431
3,16,4,Europe,Champions League,male,0,0,2018/2019,2026-05-15 15:54:04.598614,2021-06-13 16:17:31.694000,NaN,2026-05-15 15:54:04.598614
4,16,1,Europe,Champions League,male,0,0,2017/2018,2024-02-13 02:35:28.134882,2021-06-13 16:17:31.694000,NaN,2024-02-13 02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
75,35,75,Europe,UEFA Europa League,male,0,0,1988/1989,2026-04-11 12:48:10.012987,2021-06-13 16:17:31.694000,NaN,2026-04-11 12:48:10.012987
76,53,315,Europe,UEFA Women's Euro,female,0,1,2025,2026-04-27 22:02:42.690507,2026-04-27 22:03:28.087062,2026-04-27 22:03:28.087062,2026-04-27 22:02:42.690507
77,53,106,Europe,UEFA Women's Euro,female,0,1,2022,2026-05-05 03:03:04.199896,2026-05-05 03:05:32.480837,2026-05-05 03:05:32.480837,2026-05-05 03:03:04.199896
78,72,107,International,Women's World Cup,female,0,1,2023,2026-05-03 13:51:31.021141,2026-05-03 13:55:52.303219,2026-05-03 13:55:52.303219,2026-05-03 13:51:31.021141
79,72,30,International,Women's World Cup,female,0,1,2019,2026-05-15 15:31:40.299642,2021-06-13 16:17:31.694000,NaN,2026-05-15 15:31:40.299642

In [111]:
connection = sqlite3.connect('../dbs/competitions.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('SELECT * FROM matches', connection)

# 3. Always close the connection when finished
connection.close()

In [113]:
df

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,22912,2019-06-01,21:00:00.000,0,2,available,scheduled,2024-02-12 12:58:06.654567,2021-06-13 16:17:31.694000,13,...,Argentina,94,Jürgen Klopp,None,1967-06-16,85,Germany,1.1.0,2,2

In [ ]:
import sqlite3

# Connect to the database file
conn = sqlite3.connect('../dbs/competitions.db')
cursor = conn.cursor()

# Get list of all tables
cursor.execute("""DELETE FROM staging_competitions""")
conn.commit()
conn.close()

In [115]:
import sqlite3

# Connect to the database file
conn = sqlite3.connect('../dbs/competitions.db')
cursor = conn.cursor()

# Get list of all tables
cursor.execute("""DELETE FROM competitions""")
conn.commit()
conn.close()

In [102]:
import sqlite3

# Connect to the database file
conn = sqlite3.connect('../dbs/competitions.db')
cursor = conn.cursor()

cursor.execute("""DROP TABLE IF EXISTS competitions""")
conn.commit()

# Get list of all tables
cursor.execute("""CREATE TABLE competitions AS 
               SELECT * FROM staging_competitions""")
conn.commit()

# Get list of all tables
cursor.execute("""DELETE FROM competitions""")
conn.commit()

conn.close()