In [2]:
import sqlite3
import pandas as pd

pd.set_option('display.max_columns', None)

In [ ]:
connection = sqlite3.connect('../dbs/bronze.db') 
connection.cursor().execute('DROP TABLE competitions')
connection.cursor().execute('DROP TABLE matches')

In [32]:
connection = sqlite3.connect('../dbs/silver.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('SELECT COUNT(*) FROM events', connection)

# 3. Always close the connection when finished
connection.close()

df

   COUNT(*)
0    234637

In [30]:
connection = sqlite3.connect('../dbs/bronze.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('SELECT * FROM events WHERE id = "001b722a-126d-4e94-a20b-55ccfc3f45d8"', connection)

# 3. Always close the connection when finished
connection.close()

df

,id,period,timestamp,minute,second,type,possession,possession_team,play_pattern,team,team_id,player,player_id,position,tactics,location,duration,under_pressure,off_camera,out,counterpress,pass_recipient,pass_recipient_id,pass_length,pass_angle,pass_height,pass_end_location,pass_body_part,pass_type,pass_outcome,pass_technique,pass_switch,pass_cross,pass_assisted_shot_id,pass_shot_assist,pass_inswinging,pass_outswinging,pass_cut_back,pass_deflected,pass_through_ball,carry_end_location,shot_end_location,shot_statsbomb_xg,shot_outcome,shot_type,shot_body_part,shot_technique,shot_first_time,shot_key_pass_id,shot_aerial_won,shot_freeze_frame,goalkeeper_position,goalkeeper_type,goalkeeper_outcome,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_technique,dribble_outcome,dribble_overrun,dribble_nutmeg,duel_type,duel_outcome,50_50,block_deflection,block_offensive,clearance_head,clearance_left_foot,clearance_right_foot,clearance_body_part,clearance_aerial_won,ball_receipt_outcome,ball_recovery_recovery_failure,ball_recovery_offensive,foul_committed_type,foul_committed_advantage,foul_committed_card,foul_committed_penalty,foul_won_advantage,foul_won_defensive,interception_outcome,miscontrol_aerial_won,injury_stoppage_in_chain,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,related_events,match_id,data_valid_from_utc,data_valid_to_utc
0,001b722a-126d-4e94-a20b-55ccfc3f45d8,1,00:03:36.020,3,36,Carry,8,Ecuador,From Goal Kick,Senegal,787,Pathé Ismaël Ciss,31751,Right Defensive Midfield,null,"[36.7, 24.5]",2.618976,1,None,None,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,"[37.7, 8.8]",null,None,None,None,None,None,None,None,None,null,None,None,None,None,null,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[""ae18bca7-36a4-4fdd-b7ed-f9f6e8b12911"", ""833e...",3857267,2026-08-04 13:37:45.264843,2026-08-04 13:45:52.575567
1,001b722a-126d-4e94-a20b-55ccfc3f45d8,1,00:03:36.020,3,36,Carry,8,Ecuador,From Goal Kick,Senegal,787,Pathé Ismaël Ciss,31751,Right Defensive Midfield,null,"[36.7, 24.5]",2.618976,1,None,None,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,"[37.7, 8.8]",null,None,None,None,None,None,None,None,None,null,None,None,None,None,null,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[""ae18bca7-36a4-4fdd-b7ed-f9f6e8b12911"", ""833e...",3857267,2026-08-04 13:40:29.748350,2026-08-04 13:45:52.575567
2,001b722a-126d-4e94-a20b-55ccfc3f45d8,1,00:03:36.020,3,36,Carry,8,Ecuador,From Goal Kick,Senegal,787,Pathé Ismaël Ciss,31751,Right Defensive Midfield,null,"[36.7, 24.5]",2.618976,1,None,None,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,"[37.7, 8.8]",null,None,None,None,None,None,None,None,None,null,None,None,None,None,null,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[""ae18bca7-36a4-4fdd-b7ed-f9f6e8b12911"", ""833e...",3857267,2026-08-04 13:42:49.718446,2026-08-04 13:45:52.575567
3,001b722a-126d-4e94-a20b-55ccfc3f45d8,1,00:03:36.020,3,36,Carry,8,Ecuador,From Goal Kick,Senegal,787,Pathé Ismaël Ciss,31751,Right Defensive Midfield,null,"[36.7, 24.5]",2.618976,1,None,None,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,"[37.7, 8.8]",null,None,None,None,None,None,None,None,None,null,None,None,None,None,null,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[""ae18bca7-36a4-4fdd-b7ed-f9f6e8b12911"", ""833e...",3857267,2026-08-04 13:43:18.301228,2026-08-04 13:45:52.575567
4,001b722a-126d-4e94-a20b-55ccfc3f45d8,1,00:03:36.020,3,36,Carry,8,Ecuador,From Goal Kick,Senegal,787,Pathé Ismaël Ciss,31751,Right Defensive Midfield,null,"[36.7, 24.5]",2.618976,1,None,None,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,"[37.7, 8.8]",null,None,None,None,None,None,None,None,None,null,None,None,None,None,null,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[""ae18bca7-36a4-4fdd-b7ed-f9f6e8b12911"", ""833e...",3857267,2026-08-04 13:45:52.576567,NaN