In [1]:
import sqlite3
import pandas as pd

pd.set_option('display.max_columns', None)

In [ ]:
connection = sqlite3.connect('../dbs/bronze.db') 
connection.cursor().execute('DROP TABLE competitions')
connection.cursor().execute('DROP TABLE matches')

In [23]:
connection = sqlite3.connect('../data_extraction_workflow/dbs/gold.db')


# 2. Read query directly into a DataFrame
df = pd.read_sql_query('''
    SELECT player_id, COUNT(*) FROM player_lookup
    GROUP BY player_id
    HAVING COUNT(*) > 1
    ''', connection)

# 2. Read query directly into a DataFrame
df = pd.read_sql_query(f'''
    SELECT * FROM player_lookup
    WHERE player_id IN ({",".join(map(str, df["player_id"]))})
    ''', connection)


# 3. Always close the connection when finished
connection.close()

df

Empty DataFrame
Columns: [player_id, player_name, player_nickname]
Index: []

In [21]:
",".join(list(df.player_id))

TypeError: sequence item 0: expected str instance, int found

In [11]:
connection = sqlite3.connect('../data_extraction_workflow/dbs/gold.db')


# 2. Read query directly into a DataFrame
df = pd.read_sql_query('''
    SELECT * FROM combined_results
''', connection)

# 3. Always close the connection when finished
connection.close()

df.head(20)

   cst_composite_id  competition_id  season_id   country_name  \
0          43-3-768              43          3  International
1          43-3-769              43          3  International
2          43-3-770              43          3  International
3          43-3-770              43          3  International
4          43-3-771              43          3  International
5          43-3-772              43          3  International
6          43-3-773              43          3  International
7          43-3-774              43          3  International
8          43-3-774              43          3  International
9          43-3-775              43          3  International
10         43-3-775              43          3  International
11         43-3-776              43          3  International
12         43-3-777              43          3  International
13         43-3-777              43          3  International
14         43-3-778              43          3  International
15         43-3-779              43          3  International
16         43-3-780              43          3  International
17         43-3-781              43          3  International
18         43-3-782              43          3  International
19         43-3-783              43          3  International

   competition_name season_name          competition  team_id    team_name  \
0    FIFA World Cup        2018  FIFA World Cup 2018      768      England
1    FIFA World Cup        2018  FIFA World Cup 2018      769     Colombia
2    FIFA World Cup        2018  FIFA World Cup 2018      770      Germany
3    FIFA World Cup        2018  FIFA World Cup 2018      770      Germany
4    FIFA World Cup        2018  FIFA World Cup 2018      771       France
5    FIFA World Cup        2018  FIFA World Cup 2018      772        Spain
6    FIFA World Cup        2018  FIFA World Cup 2018      773  Switzerland
7    FIFA World Cup        2018  FIFA World Cup 2018      774        Egypt
8    FIFA World Cup        2018  FIFA World Cup 2018      774        Egypt
9    FIFA World Cup        2018  FIFA World Cup 2018      775      Nigeria
10   FIFA World Cup        2018  FIFA World Cup 2018      775      Nigeria
11   FIFA World Cup        2018  FIFA World Cup 2018      776      Denmark
12   FIFA World Cup        2018  FIFA World Cup 2018      777      Tunisia
13   FIFA World Cup        2018  FIFA World Cup 2018      777      Tunisia
14   FIFA World Cup        2018  FIFA World Cup 2018      778        Japan
15   FIFA World Cup        2018  FIFA World Cup 2018      779    Argentina
16   FIFA World Cup        2018  FIFA World Cup 2018      780     Portugal
17   FIFA World Cup        2018  FIFA World Cup 2018      781       Brazil
18   FIFA World Cup        2018  FIFA World Cup 2018      782      Belgium
19   FIFA World Cup        2018  FIFA World Cup 2018      783      Uruguay

    matches_played  win_non_pens  win_in_pens  draw  lost_non_pens  \
0                7             3            1     0              3
1                4             2            0     0              1
2                3             1            0     0              2
3                3             1            0     0              2
4                7             6            0     1              0
5                4             1            0     2              0
6                4             1            0     2              1
7                3             0            0     0              3
8                3             0            0     0              3
9                3             1            0     0              2
10               3             1            0     0              2
11               4             1            0     2              0
12               3             1            0     0              2
13               3             1            0     0              2
14               4             1            0     1              2
15               4             1            0     1              2
16               4             1            0     2              1
17               5             3            0     1              1
18               7             6            0     0              1
19               5             4            0     0              1

    lost_in_pens    stage_reached  max_competition_stage_ranking  wins  losses
0              0        4th Place                             10     4       3
1              1      Round of 16                              6     2       2
2              0  1st Group Stage                              1     1       2
3              0      Group Stage                              1     1       2
4              0        1st Place                             14     6       0
5              1      Round of 16                              6     1       1
6              0      Round of 16                              6     1       1
7              0  1st Group Stage                              1     0       3
8              0      Group Stage                              1     0       3
9              0  1st Group Stage                              1     1       2
10             0      Group Stage                              1     1       2
11             1      Round of 16                              6     1       1
12             0  1st Group Stage                              1     1       2
13             0      Group Stage                              1     1       2
14             0      Round of 16                              6     1       2
15             0      Round of 16                              6     1       2
16             0      Round of 16                              6     1       1
17             0   Quarter-finals                              7     3       1
18             0        3rd Place                             12     6       1
19             0   Quarter-finals                              7     4       1

In [11]:
connection = sqlite3.connect('../data_extraction_workflow/dbs/silver.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('''
            SELECT 
                competition_stage
                ,competition_stage_ranking
            FROM 
                combined
            GROUP BY 
                competition_stage
                ,competition_stage_ranking
''', connection)

# 3. Always close the connection when finished
connection.close()

df

  competition_stage  competition_stage_ranking
0   1st Group Stage                          1
1   3rd Place Final                          9
2             Final                         10
3       Group Stage                          1
4    Quarter-finals                          7
5       Round of 16                          6
6       Semi-finals                          8

In [33]:
connection = sqlite3.connect('../dbs/silver.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('SELECT * FROM combined WHERE id = "001b722a-126d-4e94-a20b-55ccfc3f45d8"', connection)

# 3. Always close the connection when finished
connection.close()

df

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_id,match_date,kick_off,home_score,away_score,match_status,match_week,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,id,period,timestamp,minute,second,type,possession,possession_team,play_pattern,team,team_id,player,player_id,position,tactics,location,duration,under_pressure,off_camera,out,counterpress,pass_recipient,pass_recipient_id,pass_length,pass_angle,pass_height,pass_end_location,pass_body_part,pass_type,pass_outcome,pass_technique,pass_switch,pass_cross,pass_assisted_shot_id,pass_shot_assist,pass_inswinging,pass_outswinging,pass_cut_back,pass_deflected,pass_through_ball,carry_end_location,shot_end_location,shot_statsbomb_xg,shot_outcome,shot_type,shot_body_part,shot_technique,shot_first_time,shot_key_pass_id,shot_aerial_won,shot_freeze_frame,goalkeeper_position,goalkeeper_type,goalkeeper_outcome,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_technique,dribble_outcome,dribble_overrun,dribble_nutmeg,duel_type,duel_outcome,50_50,block_deflection,block_offensive,clearance_head,clearance_left_foot,clearance_right_foot,clearance_body_part,clearance_aerial_won,ball_receipt_outcome,ball_recovery_recovery_failure,ball_recovery_offensive,foul_committed_type,foul_committed_advantage,foul_committed_card,foul_committed_penalty,foul_won_advantage,foul_won_defensive,interception_outcome,miscontrol_aerial_won,injury_stoppage_in_chain,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,related_events
0,43,106,International,FIFA World Cup,male,0,1,2022,3857267,2022-11-29,15:00:00.000,1,2,available,3,3565,Ecuador,male,A,65,Ecuador,787,Senegal,male,A,202,Senegal,10,Group Stage,1000253,Sheikh Khalifa International Stadium,185,Qatar,76,Clément Turpin,78,France,Gustavo Julio Alfaro,Aliou Cissé,2881,Gustavo Julio Alfaro,Gustavo Alfaro,1962-08-14,11,Argentina,635,Aliou Cissé,None,1976-03-24,202,Senegal,001b722a-126d-4e94-a20b-55ccfc3f45d8,1,00:03:36.020,3,36,Carry,8,Ecuador,From Goal Kick,Senegal,787,Pathé Ismaël Ciss,31751,Right Defensive Midfield,null,"[36.7, 24.5]",2.618976,1,None,None,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,"[37.7, 8.8]",null,None,None,None,None,None,None,None,None,null,None,None,None,None,null,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[""ae18bca7-36a4-4fdd-b7ed-f9f6e8b12911"", ""833e..."

In [4]:
import sqlite3
import pandas as pd

pd.set_option('display.max_columns', None)

combined_passes_query = f"""
 -- SQLite
SELECT 
    *
FROM 
    combined_passes
"""

In [5]:
connection = sqlite3.connect('../dbs/gold.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query(combined_passes_query, connection)

# 3. Always close the connection when finished
connection.close()

df

,competition_id,season_id,country_name,competition_name,season_name,match_id,match_date,kick_off,home_score,away_score,match_week,home_team,away_team,winning_team_id,winning_team,competition_stage,id,period,which_half,timestamp,minute,second,type,possession,possession_team,play_pattern,team,team_id,part_of_winning_team,player,player_id,position,location,duration,under_pressure,off_camera,out,counterpress,pass_recipient,pass_recipient_id,pass_length,pass_angle,pass_direction,pass_height,pass_end_location,pass_end_sector,pass_end_sector_rank,pass_body_part,pass_type,pass_outcome,pass_technique,pass_switch,pass_cross,pass_assisted_shot_id,pass_shot_assist,pass_inswinging,pass_outswinging,pass_cut_back,pass_deflected,pass_through_ball
0,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,00391272-8571-43e0-be07-d5a0b48c384f,1,1st Half,00:10:39.457,10,39,Pass,24,England,Regular Play,England,768,1,Jordan Pickford,3468,Goalkeeper,"[31.1, 46.4]",1.549342,NaN,NaN,None,NaN,Harry Maguire,3336.0,15.435349,-1.136126,Forward,Ground Pass,"[37.6, 32.4]",Defensive 3rd,3,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
1,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,00df2def-4426-45b6-9305-8f6ef9a6a394,1,1st Half,00:37:05.151,37,5,Pass,61,England,Regular Play,England,768,1,Phil Foden,4354,Right Wing,"[74.7, 72.4]",1.309154,NaN,NaN,None,NaN,Jordan Brian Henderson,3532.0,13.461427,0.470292,Forward,Ground Pass,"[86.7, 78.5]",Final 3rd,1,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
2,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,0117d34f-2ee9-4681-83f7-bb3e1c06f091,1,1st Half,00:21:39.019,21,39,Pass,35,England,From Free Kick,England,768,1,Jordan Brian Henderson,3532,Right Center Midfield,"[110.0, 78.8]",1.497853,NaN,NaN,None,NaN,Kyle Walker,3205.0,14.257980,-2.951075,Backward,Ground Pass,"[96.0, 76.1]",Final 3rd,1,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
3,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,01416e43-e4da-4b30-a712-1792772e20fa,2,2nd Half,00:48:12.399,93,12,Pass,156,England,From Free Kick,England,768,1,Jude Bellingham,30714,Left Center Midfield,"[56.0, 33.1]",0.874044,NaN,NaN,None,NaN,Jack Grealish,9638.0,18.519450,-0.113639,Forward,Ground Pass,"[74.4, 31.0]",Middle 3rd,2,Right Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
4,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,01fb8c30-333b-4290-a84b-caefbb85e6b3,2,2nd Half,00:20:44.941,65,44,Pass,116,England,Regular Play,England,768,1,Trent Alexander-Arnold,3664,Right Back,"[34.1, 55.9]",1.565596,1.0,NaN,None,NaN,Marcus Rashford,3318.0,13.519245,0.370891,Forward,High Pass,"[46.7, 60.8]",Middle 3rd,2,NaN,Recovery,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,fe7cd9b5-195a-4fe3-b48d-18e15f6b5b5c,1,1st Half,00:02:03.976,2,3,Pass,9,England,Regular Play,England,768,1,Jordan Pickford,3468,Goalkeeper,"[23.8, 37.6]",0.980531,NaN,NaN,None,NaN,Harry Maguire,3336.0,7.473286,-1.355030,Forward,Ground Pass,"[25.4, 30.3]",Defensive 3rd,3,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
977,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,fe84aab4-fe90-41df-a663-e162a536f67b,2,2nd Half,00:02:10.417,47,10,Pass,92,England,From Free Kick,England,768,1,Luke Shaw,3382,Left Back,"[34.1, 3.1]",1.650400,NaN,NaN,None,NaN,Harry Maguire,3336.0,15.071164,2.459598,Backward,Ground Pass,"[22.4, 12.6]",Defensive 3rd,3,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
978,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,ff0b51d4-3173-46e4-b1e5-4b19bfc71e95,2,2nd Half,00:20:03.976,65,3,Pass,114,Wales,From Free Kick,Wales,907,0,Daniel Ward,9914,Goalkeeper,"[26.0, 15.8]",3.701090,NaN,NaN,None,NaN,Kieffer Roberto Francisco Moore,3853.0,63.764020,-0.182939,Forward,Ground Pass,"[88.7, 4.2]",Final 3rd,1,Right Foot,Free Kick,Incomplete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
979,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,ff2ca628-2b5a-4620-b3a4-7b5db9e5f8d9,1,1st Half,00:31:48.157,31,48,Pass,55,Wales,Regular Play,Wales,907,0,Joe Rodon,11250,Left Center Back,"[21.8, 28.7]",1.309225,NaN,NaN,None,NaN,Ben Davies,3086.0,22.986954,-1.111040,Forward,Ground Pass,"[32.0, 8.1]",Defensive 3rd,3,Right Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
980,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,ff86d751-f1e9-4018-a693-1940c91d1389,1,1st Half,00:25:21.961,25,21,Pass,40,England,Regular Play,England,768,1,Kyle Walker,3205,Right Back,"[81.0, 65.2]",0.984402,NaN,NaN,None,NaN,Phil Foden,4354.0,13.403358,0.949680,Forward,Ground Pass,"[88.8, 76.1]",Final 3rd,1,Right Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN

In [6]:
df.to_csv('passes.csv')