In [1]:
import sqlite3
import pandas as pd

pd.set_option('display.max_columns', None)

In [ ]:
connection = sqlite3.connect('../dbs/bronze.db') 
connection.cursor().execute('DROP TABLE competitions')
connection.cursor().execute('DROP TABLE matches')

In [3]:
connection = sqlite3.connect('../data_extraction_workflow/dbs/bronze.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('SELECT * FROM lineups', connection)

# 3. Always close the connection when finished
connection.close()

df

,match_id,player_id,player_name,player_nickname,jersey_number,country,first_yellow_time,first_yellow_reason,first_yellow_period,second_yellow_time,second_yellow_reason,second_yellow_period,red_card_time,red_card_reason,red_card_period,starting_xi,sub_off,sub_on,removed_due_to_red_card,ended_game,data_valid_from_utc,data_valid_to_utc
0,3857276,3625,Sofiane Boufal,Sofiane Boufal,17,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,1.0,64:10,NaN,None,0.0,2026-08-11 19:43:14.489451,None
1,3857276,3634,Abdelhamid Sabiri,Abdelhamid Sabiri,11,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,1.0,64:28,NaN,None,0.0,2026-08-11 19:43:14.489451,None
2,3857276,5219,Romain Saïss,Romain Saïss,6,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,1.0,NaN,NaN,None,1.0,2026-08-11 19:43:14.489451,None
3,3857276,5233,Munir Mohand Mohamedi,Munir,12,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
4,3857276,5234,Sofyan Amrabat,Sofyan Amrabat,4,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,1.0,NaN,NaN,None,1.0,2026-08-11 19:43:14.489451,None
5,3857276,5237,Hakim Ziyech,Hakim Ziyech,7,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,1.0,75:36,NaN,None,0.0,2026-08-11 19:43:14.489451,None
6,3857276,5245,Achraf Hakimi Mouh,Achraf Hakimi,2,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,1.0,84:55,NaN,None,0.0,2026-08-11 19:43:14.489451,None
7,3857276,6301,Youssef En-Nesyri,Youssef En-Nesyri,19,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,1.0,NaN,NaN,None,1.0,2026-08-11 19:43:14.489451,None
8,3857276,6785,Yassine Bounou,Yassine Bounou,1,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,1.0,NaN,NaN,None,1.0,2026-08-11 19:43:14.489451,None
9,3857276,7459,Jawad El Yamiq,Jawad El Yamiq,18,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,0.0,NaN,75:48,None,1.0,2026-08-11 19:43:14.489451,None
10,3857276,12149,Nayef Aguerd,Nayef Aguerd,5,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,1.0,NaN,NaN,None,1.0,2026-08-11 19:43:14.489451,None
11,3857276,15890,Noussair Mazraoui,Noussair Mazraoui,3,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,1.0,NaN,NaN,None,1.0,2026-08-11 19:43:14.489451,None
12,3857276,21214,Ilias Chair,Ilias Chair,13,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
13,3857276,21736,Zakaria Aboukhlal,Zakaria Aboukhlal,14,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,0.0,NaN,64:10,None,1.0,2026-08-11 19:43:14.489451,None
14,3857276,23774,Selim Amallah,Selim Amallah,15,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,0.0,NaN,64:28,None,1.0,2026-08-11 19:43:14.489451,None
15,3857276,31295,Yahia Attiyat allah,Yahia Attiyat allah,25,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
16,3857276,46258,Azzedine Ounahi,Azzedine Ounahi,8,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,1.0,75:48,NaN,None,0.0,2026-08-11 19:43:14.489451,None
17,3857276,59493,Abderrazak Hamdallah,Abderrazak Hamdallah,9,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,0.0,NaN,75:36,None,1.0,2026-08-11 19:43:14.489451,None
18,3857276,67700,Badr Banoun,Badr Banoun,24,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
19,3857276,102668,Yahya Jabrane,Yahya Jabrane,26,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,0.0,NaN,84:55,None,1.0,2026-08-11 19:43:14.489451,None
20,3857276,131037,Anass Zaroury,Anass Zaroury,10,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
21,3857276,139011,Ahmed Reda Tagnaouti,Ahmed Reda Tagnaouti,22,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
22,3857276,139016,Achraf Dari,Achraf Dari,20,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
23,3857276,149714,Abdessamad Ezzalzouli,Abde Ezzalzouli,16,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
24,3857276,156734,Bilal El Khannous,Bilal El Khannous,23,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
25,3857276,296254,Walid Cheddira,Walid Cheddira,21,Morocco,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
26,3857276,4106,Ike Ugbo,Ike Ugbo,12,Canada,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
27,3857276,9036,David Wallace Wotherspoon,David Wallace Wotherspoon,24,Canada,NaN,NaN,NaN,None,None,None,None,None,None,0.0,NaN,75:24,None,1.0,2026-08-11 19:43:14.489451,None
28,3857276,9922,David Junior Hoilett,Junior Hoilett,10,Canada,06:43,Foul Committed,1.0,None,None,None,None,None,None,1.0,75:24,NaN,None,0.0,2026-08-11 19:43:14.489451,None
29,3857276,11187,Stephen Antunes Eustáquio,Stephen Antunes Eustáquio,7,Canada,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
30,3857276,11846,Steven de Sousa Vitoria,Steven Vitória,5,Canada,83:49,Foul Committed,2.0,None,None,None,None,None,None,1.0,NaN,NaN,None,1.0,2026-08-11 19:43:14.489451,None
31,3857276,12365,Alphonso Davies,Alphonso Davies,19,Canada,NaN,NaN,NaN,None,None,None,None,None,None,1.0,NaN,NaN,None,1.0,2026-08-11 19:43:14.489451,None
32,3857276,12770,Jonathan Osorio,Jonathan Osorio,21,Canada,25:39,Foul Committed,1.0,None,None,None,None,None,None,1.0,65:04,NaN,None,0.0,2026-08-11 19:43:14.489451,None
33,3857276,12779,Samuel Piette,Samuel Piette,6,Canada,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
34,3857276,13885,Liam Fraser,Liam Fraser,8,Canada,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
35,3857276,15958,Milan Borjan,Milan Borjan,18,Canada,NaN,NaN,NaN,None,None,None,None,None,None,1.0,NaN,NaN,None,1.0,2026-08-11 19:43:14.489451,None
36,3857276,16120,Richie Laryea,Richie Laryea,22,Canada,NaN,NaN,NaN,None,None,None,None,None,None,0.0,NaN,65:04,None,1.0,2026-08-11 19:43:14.489451,None
37,3857276,16252,Mark Anthony Kaye,Mark Anthony Kaye,14,Canada,NaN,NaN,NaN,None,None,None,None,None,None,1.0,59:51,NaN,None,0.0,2026-08-11 19:43:14.489451,None
38,3857276,16459,Cyle Larin,Cyle Larin,17,Canada,NaN,NaN,NaN,None,None,None,None,None,None,1.0,59:47,NaN,None,0.0,2026-08-11 19:43:14.489451,None
39,3857276,23363,Liam Millar,Liam Millar,23,Canada,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
40,3857276,23640,Jonathan David,Jonathan David,20,Canada,NaN,NaN,NaN,None,None,None,None,None,None,0.0,NaN,59:47,None,1.0,2026-08-11 19:43:14.489451,None
41,3857276,23760,Derek Cornelius,Derek Cornelius,25,Canada,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
42,3857276,23828,Kamal Miller,Kamal Miller,4,Canada,NaN,NaN,NaN,None,None,None,None,None,None,1.0,NaN,NaN,None,1.0,2026-08-11 19:43:14.489451,None
43,3857276,24024,Tajon Buchanan,Tajon Buchanan,11,Canada,NaN,NaN,NaN,None,None,None,None,None,None,1.0,NaN,NaN,None,1.0,2026-08-11 19:43:14.489451,None
44,3857276,26348,Lucas Daniel Cavallini,Lucas Cavallini,9,Canada,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
45,3857276,29758,Sam Adekugbe,Sam Adekugbe,3,Canada,46:25,Foul Committed,1.0,None,None,None,None,None,None,1.0,60:12,NaN,None,0.0,2026-08-11 19:43:14.489451,None
46,3857276,31684,Atiba Hutchinson,Atiba Hutchinson,13,Canada,NaN,NaN,NaN,None,None,None,None,None,None,0.0,NaN,59:51,None,1.0,2026-08-11 19:43:14.489451,None
47,3857276,35707,Joel Waterman,Joel Waterman,26,Canada,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
48,3857276,36794,Dayne Tristan St. Clair,Dayne St. Clair,1,Canada,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
49,3857276,44703,Alistair Johnston,Alistair Johnston,2,Canada,NaN,NaN,NaN,None,None,None,None,None,None,1.0,NaN,NaN,None,1.0,2026-08-11 19:43:14.489451,None
50,3857276,49259,James Pantemis,James Pantemis,16,Canada,NaN,NaN,NaN,None,None,None,None,None,None,NaN,NaN,NaN,None,NaN,2026-08-11 19:43:14.489451,None
51,3857276,133229,Ismael Koné,Ismael Koné,15,Canada,NaN,NaN,NaN,None,None,None,None,None,None,0.0,NaN,60:12,None,1.0,2026-08-11 19:43:14.489451,None

In [33]:
connection = sqlite3.connect('../dbs/silver.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query('SELECT * FROM combined WHERE id = "001b722a-126d-4e94-a20b-55ccfc3f45d8"', connection)

# 3. Always close the connection when finished
connection.close()

df

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_id,match_date,kick_off,home_score,away_score,match_status,match_week,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,id,period,timestamp,minute,second,type,possession,possession_team,play_pattern,team,team_id,player,player_id,position,tactics,location,duration,under_pressure,off_camera,out,counterpress,pass_recipient,pass_recipient_id,pass_length,pass_angle,pass_height,pass_end_location,pass_body_part,pass_type,pass_outcome,pass_technique,pass_switch,pass_cross,pass_assisted_shot_id,pass_shot_assist,pass_inswinging,pass_outswinging,pass_cut_back,pass_deflected,pass_through_ball,carry_end_location,shot_end_location,shot_statsbomb_xg,shot_outcome,shot_type,shot_body_part,shot_technique,shot_first_time,shot_key_pass_id,shot_aerial_won,shot_freeze_frame,goalkeeper_position,goalkeeper_type,goalkeeper_outcome,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_technique,dribble_outcome,dribble_overrun,dribble_nutmeg,duel_type,duel_outcome,50_50,block_deflection,block_offensive,clearance_head,clearance_left_foot,clearance_right_foot,clearance_body_part,clearance_aerial_won,ball_receipt_outcome,ball_recovery_recovery_failure,ball_recovery_offensive,foul_committed_type,foul_committed_advantage,foul_committed_card,foul_committed_penalty,foul_won_advantage,foul_won_defensive,interception_outcome,miscontrol_aerial_won,injury_stoppage_in_chain,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,related_events
0,43,106,International,FIFA World Cup,male,0,1,2022,3857267,2022-11-29,15:00:00.000,1,2,available,3,3565,Ecuador,male,A,65,Ecuador,787,Senegal,male,A,202,Senegal,10,Group Stage,1000253,Sheikh Khalifa International Stadium,185,Qatar,76,Clément Turpin,78,France,Gustavo Julio Alfaro,Aliou Cissé,2881,Gustavo Julio Alfaro,Gustavo Alfaro,1962-08-14,11,Argentina,635,Aliou Cissé,None,1976-03-24,202,Senegal,001b722a-126d-4e94-a20b-55ccfc3f45d8,1,00:03:36.020,3,36,Carry,8,Ecuador,From Goal Kick,Senegal,787,Pathé Ismaël Ciss,31751,Right Defensive Midfield,null,"[36.7, 24.5]",2.618976,1,None,None,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,"[37.7, 8.8]",null,None,None,None,None,None,None,None,None,null,None,None,None,None,null,None,None,None,None,None,None,null,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[""ae18bca7-36a4-4fdd-b7ed-f9f6e8b12911"", ""833e..."

In [4]:
import sqlite3
import pandas as pd

pd.set_option('display.max_columns', None)

combined_passes_query = f"""
 -- SQLite
SELECT 
    *
FROM 
    combined_passes
"""

In [5]:
connection = sqlite3.connect('../dbs/gold.db')

# 2. Read query directly into a DataFrame
df = pd.read_sql_query(combined_passes_query, connection)

# 3. Always close the connection when finished
connection.close()

df

,competition_id,season_id,country_name,competition_name,season_name,match_id,match_date,kick_off,home_score,away_score,match_week,home_team,away_team,winning_team_id,winning_team,competition_stage,id,period,which_half,timestamp,minute,second,type,possession,possession_team,play_pattern,team,team_id,part_of_winning_team,player,player_id,position,location,duration,under_pressure,off_camera,out,counterpress,pass_recipient,pass_recipient_id,pass_length,pass_angle,pass_direction,pass_height,pass_end_location,pass_end_sector,pass_end_sector_rank,pass_body_part,pass_type,pass_outcome,pass_technique,pass_switch,pass_cross,pass_assisted_shot_id,pass_shot_assist,pass_inswinging,pass_outswinging,pass_cut_back,pass_deflected,pass_through_ball
0,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,00391272-8571-43e0-be07-d5a0b48c384f,1,1st Half,00:10:39.457,10,39,Pass,24,England,Regular Play,England,768,1,Jordan Pickford,3468,Goalkeeper,"[31.1, 46.4]",1.549342,NaN,NaN,None,NaN,Harry Maguire,3336.0,15.435349,-1.136126,Forward,Ground Pass,"[37.6, 32.4]",Defensive 3rd,3,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
1,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,00df2def-4426-45b6-9305-8f6ef9a6a394,1,1st Half,00:37:05.151,37,5,Pass,61,England,Regular Play,England,768,1,Phil Foden,4354,Right Wing,"[74.7, 72.4]",1.309154,NaN,NaN,None,NaN,Jordan Brian Henderson,3532.0,13.461427,0.470292,Forward,Ground Pass,"[86.7, 78.5]",Final 3rd,1,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
2,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,0117d34f-2ee9-4681-83f7-bb3e1c06f091,1,1st Half,00:21:39.019,21,39,Pass,35,England,From Free Kick,England,768,1,Jordan Brian Henderson,3532,Right Center Midfield,"[110.0, 78.8]",1.497853,NaN,NaN,None,NaN,Kyle Walker,3205.0,14.257980,-2.951075,Backward,Ground Pass,"[96.0, 76.1]",Final 3rd,1,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
3,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,01416e43-e4da-4b30-a712-1792772e20fa,2,2nd Half,00:48:12.399,93,12,Pass,156,England,From Free Kick,England,768,1,Jude Bellingham,30714,Left Center Midfield,"[56.0, 33.1]",0.874044,NaN,NaN,None,NaN,Jack Grealish,9638.0,18.519450,-0.113639,Forward,Ground Pass,"[74.4, 31.0]",Middle 3rd,2,Right Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
4,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,01fb8c30-333b-4290-a84b-caefbb85e6b3,2,2nd Half,00:20:44.941,65,44,Pass,116,England,Regular Play,England,768,1,Trent Alexander-Arnold,3664,Right Back,"[34.1, 55.9]",1.565596,1.0,NaN,None,NaN,Marcus Rashford,3318.0,13.519245,0.370891,Forward,High Pass,"[46.7, 60.8]",Middle 3rd,2,NaN,Recovery,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,fe7cd9b5-195a-4fe3-b48d-18e15f6b5b5c,1,1st Half,00:02:03.976,2,3,Pass,9,England,Regular Play,England,768,1,Jordan Pickford,3468,Goalkeeper,"[23.8, 37.6]",0.980531,NaN,NaN,None,NaN,Harry Maguire,3336.0,7.473286,-1.355030,Forward,Ground Pass,"[25.4, 30.3]",Defensive 3rd,3,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
977,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,fe84aab4-fe90-41df-a663-e162a536f67b,2,2nd Half,00:02:10.417,47,10,Pass,92,England,From Free Kick,England,768,1,Luke Shaw,3382,Left Back,"[34.1, 3.1]",1.650400,NaN,NaN,None,NaN,Harry Maguire,3336.0,15.071164,2.459598,Backward,Ground Pass,"[22.4, 12.6]",Defensive 3rd,3,Left Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
978,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,ff0b51d4-3173-46e4-b1e5-4b19bfc71e95,2,2nd Half,00:20:03.976,65,3,Pass,114,Wales,From Free Kick,Wales,907,0,Daniel Ward,9914,Goalkeeper,"[26.0, 15.8]",3.701090,NaN,NaN,None,NaN,Kieffer Roberto Francisco Moore,3853.0,63.764020,-0.182939,Forward,Ground Pass,"[88.7, 4.2]",Final 3rd,1,Right Foot,Free Kick,Incomplete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
979,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,ff2ca628-2b5a-4620-b3a4-7b5db9e5f8d9,1,1st Half,00:31:48.157,31,48,Pass,55,Wales,Regular Play,Wales,907,0,Joe Rodon,11250,Left Center Back,"[21.8, 28.7]",1.309225,NaN,NaN,None,NaN,Ben Davies,3086.0,22.986954,-1.111040,Forward,Ground Pass,"[32.0, 8.1]",Defensive 3rd,3,Right Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN
980,43,106,International,FIFA World Cup,2022,3857261,2022-11-29,19:00:00.000,0,3,3,Wales,England,768,England,Group Stage,ff86d751-f1e9-4018-a693-1940c91d1389,1,1st Half,00:25:21.961,25,21,Pass,40,England,Regular Play,England,768,1,Kyle Walker,3205,Right Back,"[81.0, 65.2]",0.984402,NaN,NaN,None,NaN,Phil Foden,4354.0,13.403358,0.949680,Forward,Ground Pass,"[88.8, 76.1]",Final 3rd,1,Right Foot,NaN,Success,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN

In [6]:
df.to_csv('passes.csv')